import { StyleSheet } from 'react-native';
import type { ThemeContextType } from '@src/constants/Theme';

type AppColors = ThemeContextType['colors'];

export const createStyles = (colors: AppColors, isDark?: boolean) => StyleSheet.create({
  container: {
    backgroundColor: colors.background.card,
    borderRadius: 12,
    marginBottom: 16,
    padding: 16,
    shadowColor: colors.neutral[900],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: isDark ? colors.neutral[700] : colors.neutral[200],
  },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text.secondary,
    textTransform: 'uppercase',
    letterSpacing: 0,
    marginBottom: 8,
  },
  selector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: isDark ? colors.neutral[100] : colors.neutral[50],
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 56,
    borderWidth: 1,
    borderColor: isDark ? colors.neutral[700] : colors.neutral[300],
  },
  selectorIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: isDark ? colors.neutral[700] : colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  selectorCopy: {
    flex: 1,
    minWidth: 0,
  },
  selectorText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text.primary,
  },
  selectorSubtext: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '500',
    color: colors.text.secondary,
  },
  chevron: {
    marginLeft: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.background.overlay,
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.background.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? colors.neutral[700] : colors.neutral[200],
  },
  closeButtonTouch: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text.primary,
  },
  closeButton: {
    fontSize: 20,
    color: colors.text.secondary,
    padding: 4,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 16,
    marginBottom: 8,
    paddingHorizontal: 12,
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: isDark ? colors.neutral[100] : colors.neutral[50],
    borderWidth: 1,
    borderColor: isDark ? colors.neutral[700] : colors.neutral[200],
  },
  searchInput: {
    flex: 1,
    minHeight: 44,
    marginLeft: 8,
    fontSize: 15,
    fontWeight: '500',
    color: colors.text.primary,
    paddingVertical: 0,
  },
  clientList: {
    maxHeight: 400,
  },
  clientListContent: {
    paddingBottom: 12,
  },
  clientItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 64,
    borderBottomWidth: 1,
    borderBottomColor: isDark ? colors.neutral[700] : colors.neutral[100],
  },
  clientItemSelected: {
    backgroundColor: colors.status.success + '10',
  },
  clientIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: isDark ? colors.neutral[700] : colors.primary[50],
  },
  clientInfo: {
    flex: 1,
    minWidth: 0,
  },
  clientItemText: {
    fontSize: 16,
    color: colors.text.primary,
    fontWeight: '700',
  },
  clientItemTextSelected: {
    color: colors.status.success,
    fontWeight: '600',
  },
  clientMeta: {
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: 4,
  },
  clientEmptyState: {
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  clientEmptyText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: colors.text.secondary,
    textAlign: 'center',
  },
});
