import { StyleSheet } from "react-native";
import { Fonts } from "@src/constants/Fonts";

export const createStyles = (colors: any, isDark?: boolean) => StyleSheet.create({
  card: {
    backgroundColor: colors.background.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    shadowColor: colors.neutral[900],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  promoCode: {
    fontSize: 18,
    fontFamily: Fonts.BOLD,
    color: colors.text.primary,
    letterSpacing: 1,
  },
  promoName: {
    fontSize: 14,
    fontFamily: Fonts.REGULAR,
    color: colors.text.secondary,
    marginTop: 2,
  },
  badgeRow: {
    flexDirection: "row",
    gap: 6,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  badgeText: {
    fontSize: 11,
    fontFamily: Fonts.bold,
    textTransform: "uppercase",
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    gap: 8,
  },
  cardRowText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    color: colors.text.secondary,
    flex: 1,
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.neutral[100],
    paddingTop: 12,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.primary.main,
    backgroundColor: colors.primary.main + "15",
  },
  editButtonText: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    color: colors.primary.main,
  },
  deactivateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.status.error + "40",
    backgroundColor: colors.status.error + "12",
  },
  deactivateButtonText: {
    fontSize: 14,
    fontFamily: Fonts.bold,
    color: colors.status.error,
  },
  usageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  usageTrack: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    overflow: "hidden",
  },
  usageFill: {
    height: "100%",
    borderRadius: 3,
  },
  usageText: {
    fontSize: 12,
    fontFamily: Fonts.bold,
    color: colors.text.secondary,
    minWidth: 45,
    textAlign: "right",
  },
  statsButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.primary.main + "10",
  },
  statsButtonText: {
    fontSize: 13,
    fontFamily: Fonts.bold,
    color: colors.primary.main,
  },
  cloneButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.accent.gold + "12",
  },
  cloneButtonText: {
    fontSize: 13,
    fontFamily: Fonts.bold,
    color: colors.accent.goldDark,
  },
});
