import { StyleSheet } from 'react-native';
import { Theme } from '@src/constants/Theme';

export const createStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.default,
  },
  keyboardView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing['2xl'],
    borderBottomLeftRadius: Theme.radius['3xl'],
    borderBottomRightRadius: Theme.radius['3xl'],
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.full,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContent: {
    flex: 1,
    marginLeft: Theme.spacing.lg,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: 'Theme.colors.text.inverse',
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.8)',
    marginTop: Theme.spacing.xs,
  },
  headerIcon: {
    opacity: 0.3,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: Theme.spacing.lg,
    paddingBottom: Theme.spacing['4xl'],
  },
  formCard: {
    borderRadius: Theme.radius['2xl'],
    backgroundColor: colors.background.card,
    ...Theme.shadows.md,
  },
  formContent: {
    padding: Theme.spacing.lg,
  },
  inputContainer: {
    marginBottom: Theme.spacing.lg,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.neutral[700],
    marginBottom: Theme.spacing.sm,
  },
  required: {
    color: colors.status.error,
  },
  // Phase 3: Mode Selection Styles
  modeSelectionContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  modeButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Theme.spacing.lg,
    borderWidth: 2,
    borderColor: colors.neutral[200],
    borderRadius: Theme.radius.xl,
    backgroundColor: colors.background.card,
    gap: Theme.spacing.sm,
  },
  modeButtonError: {
    borderColor: colors.status.error,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.neutral[600],
  },
  modeCheckBadge: {
    position: 'absolute',
    top: Theme.spacing.sm,
    right: Theme.spacing.sm,
    width: 20,
    height: 20,
    borderRadius: Theme.radius.full,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Phase 3: Route Selection Styles
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.neutral[200],
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    backgroundColor: colors.background.card,
  },
  dropdownButtonError: {
    borderColor: colors.status.error,
  },
  dropdownButtonLoading: {
    backgroundColor: colors.neutral[50],
  },
  dropdownButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  dropdownButtonText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.neutral[800],
  },
  dropdownButtonPlaceholder: {
    color: colors.neutral[400],
  },
  menuContent: {
    borderRadius: Theme.radius.lg,
    backgroundColor: colors.background.card,
    width: '85%',
  },
  routeMenuItem: {
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral[100],
  },
  noRoutesContainer: {
    marginTop: Theme.spacing.sm,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.status.warning + '15',
    borderRadius: Theme.radius.md,
    gap: Theme.spacing.sm,
  },
  noRoutesText: {
    fontSize: 13,
    color: colors.neutral[700],
    lineHeight: 18,
    marginLeft: Theme.spacing.lg,
  },
  createRouteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary[500],
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.sm,
    marginLeft: Theme.spacing.lg,
    gap: Theme.spacing.xs,
    ...Theme.shadows.sm,
  },
  createRouteButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'Theme.colors.text.inverse',
  },
  selectedRouteContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary[50],
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: colors.primary[200],
  },
  selectedRouteContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  selectedRouteIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.lg,
    backgroundColor: colors.primary[500],
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedRouteInfo: {
    marginLeft: Theme.spacing.md,
    flex: 1,
  },
  selectedRouteName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.neutral[800],
  },
  selectedRouteDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginTop: 2,
  },
  selectedRouteMeta: {
    fontSize: 13,
    color: colors.primary[600],
    fontWeight: '500',
  },
  selectedRoutePath: {
    fontSize: 13,
    color: colors.neutral[500],
  },
  clearRouteButton: {
    padding: Theme.spacing.xs,
  },
  routeDescriptionContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.sm,
    marginTop: -Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
    padding: Theme.spacing.md,
    backgroundColor: colors.neutral[50],
    borderRadius: Theme.radius.md,
  },
  routeDescriptionText: {
    flex: 1,
    fontSize: 13,
    color: colors.neutral[600],
    lineHeight: 18,
  },
  readOnlyField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    backgroundColor: colors.neutral[50],
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  readOnlyText: {
    fontSize: 15,
    fontWeight: '500',
    color: colors.neutral[700],
  },
  divider: {
    marginVertical: Theme.spacing.lg,
    backgroundColor: colors.neutral[200],
  },
  searchBar: {
    borderRadius: Theme.radius.md,
    backgroundColor: colors.neutral[50],
    elevation: 0,
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  searchInput: {
    fontSize: 15,
    color: colors.neutral[800],
  },
  dropdownCard: {
    marginTop: Theme.spacing.sm,
    borderRadius: Theme.radius.lg,
    maxHeight: 220,
    ...Theme.shadows.md,
  },
  dropdownLoading: {
    padding: Theme.spacing.xl,
    alignItems: 'center',
  },
  dropdownLoadingText: {
    marginTop: Theme.spacing.sm,
    fontSize: 14,
    color: colors.neutral[500],
  },
  dropdownEmpty: {
    padding: Theme.spacing.xl,
    alignItems: 'center',
  },
  dropdownEmptyText: {
    marginTop: Theme.spacing.sm,
    fontSize: 14,
    color: colors.neutral[500],
    textAlign: 'center',
  },
  consigneeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral[100],
  },
  consigneeItemIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.lg,
    backgroundColor: colors.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
  },
  consigneeItemContent: {
    flex: 1,
    marginLeft: Theme.spacing.md,
  },
  consigneeItemName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.neutral[800],
  },
  consigneeItemPhone: {
    fontSize: 13,
    color: colors.neutral[500],
    marginTop: 2,
  },
  consigneeItemAddress: {
    fontSize: 12,
    color: colors.neutral[400],
    marginTop: 2,
  },
  selectedConsigneeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary[50],
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: colors.primary[200],
  },
  selectedConsigneeContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedConsigneeIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.lg,
    backgroundColor: colors.primary[500],
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedConsigneeInfo: {
    marginLeft: Theme.spacing.md,
  },
  selectedConsigneeName: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.neutral[800],
  },
  selectedConsigneeLabel: {
    fontSize: 13,
    color: colors.primary[600],
    marginTop: 2,
  },
  clearConsigneeButton: {
    padding: Theme.spacing.xs,
  },
  optionalSection: {},
  optionalSectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.neutral[600],
    marginBottom: Theme.spacing.lg,
  },
  input: {
    backgroundColor: colors.background.card,
  },
  submitButtonContainer: {
    marginTop: Theme.spacing.xl,
    borderRadius: Theme.radius.full,
    overflow: 'hidden',
    ...Theme.shadows.lg,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Theme.spacing.lg,
    gap: Theme.spacing.sm,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: 'Theme.colors.text.inverse',
    letterSpacing: 0.3,
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Theme.spacing.lg,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.status.error + '12',
    borderRadius: Theme.radius.lg,
    gap: Theme.spacing.sm,
  },
  errorText: {
    fontSize: 14,
    color: colors.status.error,
    fontWeight: '500',
  },
});
