import { StyleSheet } from 'react-native';
import { Theme } from '@src/constants/Theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.neutral[50],
  },
  header: {
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.xl,
    paddingHorizontal: Theme.spacing.lg,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.md,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFF',
  },
  saveIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.8)',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: Theme.neutral.white,
    padding: Theme.spacing.sm,
    gap: Theme.spacing.sm,
    ...Theme.shadows.sm,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    gap: Theme.spacing.xs,
  },
  tabActive: {
    backgroundColor: Theme.primary[50],
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: Theme.neutral[500],
  },
  tabTextActive: {
    color: Theme.primary[600],
  },
  content: {
    flex: 1,
  },
  segmentsContainer: {
    flex: 1,
    padding: Theme.spacing.lg,
  },
  segmentsHeader: {
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
  },
  segmentsTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Theme.neutral[800],
    marginTop: Theme.spacing.sm,
  },
  segmentsSubtitle: {
    fontSize: 14,
    color: Theme.neutral[500],
    marginTop: Theme.spacing.xs,
  },
  segmentCard: {
    backgroundColor: Theme.neutral.white,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    ...Theme.shadows.sm,
  },
  segmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  segmentIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: `${Theme.status.info}15`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  segmentTitleContainer: {
    flex: 1,
  },
  segmentRoute: {
    fontSize: 16,
    fontWeight: '700',
    color: Theme.neutral[800],
  },
  segmentVessel: {
    fontSize: 13,
    color: Theme.neutral[500],
    marginTop: 2,
  },
  segmentVehicle: {
    fontSize: 13,
    color: Theme.neutral[500],
    marginTop: 2,
  },
  segmentBadge: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.full,
  },
  segmentBadgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  segmentDetails: {
    gap: Theme.spacing.sm,
  },
  segmentDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  segmentDetailText: {
    fontSize: 13,
    color: Theme.neutral[600],
  },
  fabContainer: {
    position: 'absolute',
    right: Theme.spacing.lg,
    bottom: Theme.spacing.lg,
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Theme.primary[600],
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadows.lg,
  },
  fabSecondary: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.neutral.white,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadows.md,
  },
  dialogTitle: {
    textAlign: 'center',
    fontWeight: '700',
  },
  formGroup: {
    marginBottom: Theme.spacing.md,
  },
  formLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: Theme.neutral[600],
    marginBottom: Theme.spacing.xs,
  },
  formInput: {
    backgroundColor: Theme.neutral[50],
    borderWidth: 1,
    borderColor: Theme.neutral[200],
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    fontSize: 15,
    color: Theme.neutral[800],
  },
  formSelect: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.neutral[50],
    borderWidth: 1,
    borderColor: Theme.neutral[200],
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    gap: Theme.spacing.sm,
  },
  formSelectText: {
    flex: 1,
    fontSize: 15,
    color: Theme.neutral[800],
  },
  templateCard: {
    backgroundColor: Theme.neutral.white,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
    ...Theme.shadows.sm,
  },
  templateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  templateName: {
    fontSize: 15,
    fontWeight: '700',
    color: Theme.neutral[800],
  },
  templateDescription: {
    fontSize: 12,
    color: Theme.neutral[500],
    marginTop: 2,
  },
  templateItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.neutral[50],
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.md,
  },
  templateIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Theme.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  templateInfo: {
    flex: 1,
  },
  templateStats: {
    fontSize: 11,
    color: Theme.primary[500],
    marginTop: 4,
    fontWeight: '600',
  },
  templateWaypoint: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Theme.neutral[100],
  },
  templateWaypointNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Theme.primary[100],
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.sm,
  },
  templateWaypointLocation: {
    flex: 1,
    fontSize: 14,
    color: Theme.neutral[700],
  },
  actionButtons: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.lg,
  },
  actionButton: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    alignItems: 'center',
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '600',
  },
  dialogText: {
    fontSize: 14,
    color: Theme.neutral[600],
    textAlign: 'center',
    marginBottom: Theme.spacing.lg,
  },
  saveSummary: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: Theme.neutral[50],
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
  },
  saveSummaryItem: {
    alignItems: 'center',
  },
  saveSummaryValue: {
    fontSize: 24,
    fontWeight: '800',
    color: Theme.primary[600],
  },
  saveSummaryLabel: {
    fontSize: 12,
    color: Theme.neutral[500],
    marginTop: 4,
  },
});
