import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.5)' },
  sheet: { maxHeight: '88%', padding: 16, borderTopLeftRadius: 20, borderTopRightRadius: 20 },
  handle: { width: 44, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 14 },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  kicker: { fontSize: 12, fontWeight: '800', textTransform: 'uppercase' },
  title: { fontSize: 22, fontWeight: '800', marginTop: 2 },
  close: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' },
  content: { paddingBottom: 8 },
  state: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: 12 },
  toolbar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  count: { fontSize: 13, fontWeight: '700' },
  row: { minHeight: 60, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 10, padding: 8, marginBottom: 8 },
  rowText: { flex: 1, marginLeft: 4 },
  packageCode: { fontSize: 14, fontWeight: '800' },
  packageMeta: { fontSize: 12, marginTop: 2 },
  printed: { fontSize: 11, fontWeight: '700', marginTop: 3 },
  fieldLabel: { fontSize: 12, fontWeight: '800', marginTop: 8, marginBottom: 6 },
  printerButton: { borderWidth: 1, borderRadius: 10, minHeight: 48, justifyContent: 'center', paddingHorizontal: 12 },
  printerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  printerName: { fontSize: 14, fontWeight: '700' },
  hint: { fontSize: 12, lineHeight: 17, marginTop: 8 },
  reasonInput: { marginTop: 10 },
  footer: { paddingTop: 10, borderTopWidth: StyleSheet.hairlineWidth },
  error: { fontSize: 12, marginBottom: 6 },
  printButton: { borderRadius: 10 },
});
