import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenContent: { padding: 16, gap: 12 },
  intro: { fontSize: 13, lineHeight: 19, marginBottom: 4 },
  state: { minHeight: 220, alignItems: 'center', justifyContent: 'center', gap: 10 },
  card: { borderRadius: 14, borderWidth: 1, padding: 14 },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardTitleWrap: { flex: 1 },
  name: { fontSize: 16, fontWeight: '800' },
  endpoint: { fontSize: 12, marginTop: 3 },
  badge: { borderRadius: 20, paddingHorizontal: 9, paddingVertical: 4 },
  badgeText: { fontSize: 10, fontWeight: '900' },
  metadata: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  metadataText: { fontSize: 12 },
  actions: { flexDirection: 'row', gap: 6, marginTop: 8 },
  action: { flex: 1 },
  fab: { position: 'absolute', right: 20, bottom: 24 },
  dialog: { maxHeight: '90%' },
  dialogScroll: { paddingHorizontal: 24 },
  row: { flexDirection: 'row', gap: 10 },
  half: { flex: 1 },
  input: { marginBottom: 10 },
  switchRow: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  switchLabel: { flex: 1, fontSize: 14 },
  historySection: { marginTop: 12, gap: 10, paddingBottom: 90 },
  historyTitle: { fontSize: 17, fontWeight: '800' },
  historyHelp: { fontSize: 12, lineHeight: 17, marginTop: 2 },
  emptyText: { fontSize: 13 },
  jobCard: { borderRadius: 12, borderWidth: 1, padding: 12, gap: 8 },
  jobHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  jobCode: { fontSize: 14, fontWeight: '700' },
  jobMeta: { fontSize: 11, marginTop: 3 },
  jobStatus: { fontSize: 10, fontWeight: '900' },
  jobError: { fontSize: 12, lineHeight: 17 },
  jobActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
});
