/* Hallmark - macrostructure: Command Directory - tone: operations-console - anchor hue: brand green - pre-emit critique: P5 H4 E4 S5 R4 V5 */
import { StyleSheet } from "react-native";
import { Theme } from "@src/constants/Theme";
import { Fonts } from "@src/constants/Fonts";
import type { ThemeContextType } from "@src/constants/Theme";

type AppThemeColors = ThemeContextType["colors"];

export const createMenuCategoriesStyles = (colors: AppThemeColors, isDark: boolean) =>
  StyleSheet.create({
    container: {
      marginBottom: 16,
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
      paddingHorizontal: 4,
      gap: 12,
    },
    sectionTitleWrap: {
      flex: 1,
      minWidth: 0,
    },
    sectionTitle: {
      fontSize: 16,
      fontFamily: Fonts.bold,
      color: colors.text.primary,
    },
    sectionHint: {
      fontSize: 11,
      fontFamily: Fonts.regular,
      color: colors.text.secondary,
      marginTop: 2,
    },
    directoryBadge: {
      minHeight: 44,
      minWidth: 48,
      paddingHorizontal: 10,
      borderRadius: 11,
      backgroundColor: colors.background.card,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 5,
    },
    directoryBadgeText: {
      fontSize: 12,
      fontFamily: Fonts.bold,
      color: colors.primary.main,
    },
    searchBox: {
      flexDirection: "row",
      alignItems: "center",
      minHeight: 48,
      paddingLeft: 13,
      borderRadius: 14,
      backgroundColor: colors.background.card,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 10,
      ...Theme.shadows.sm,
    },
    searchInput: {
      flex: 1,
      minHeight: 48,
      paddingVertical: 0,
      fontSize: 14,
      fontFamily: Fonts.regular,
      color: colors.text.primary,
    },
    clearButton: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 2,
    },
    pressed: {
      opacity: 0.72,
    },
    recentSearchesContainer: {
      marginTop: 10,
      marginBottom: 2,
    },
    recentSearchesHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 4,
      marginBottom: 8,
    },
    recentSearchesTitle: {
      fontSize: 11,
      fontFamily: Fonts.bold,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    recentSearchesClear: {
      fontSize: 12,
      fontFamily: Fonts.bold,
    },
    recentSearchesChips: {
      flexDirection: "row",
      gap: 8,
      paddingRight: 4,
    },
    recentSearchesChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      maxWidth: 200,
    },
    recentSearchesChipText: {
      fontSize: 13,
      fontFamily: Fonts.bold,
      maxWidth: 130,
    },
    tabsRail: {
      marginTop: 10,
      marginBottom: 12,
    },
    tabsContent: {
      gap: 8,
      paddingRight: 4,
    },
    tab: {
      minHeight: 44,
      borderRadius: 12,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background.card,
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
    },
    tabActive: {
      borderWidth: 1,
    },
    tabText: {
      fontSize: 12,
      fontFamily: Fonts.bold,
      color: colors.text.secondary,
      maxWidth: 112,
    },
    tabCount: {
      fontSize: 11,
      fontFamily: Fonts.bold,
      color: colors.text.disabled,
    },
    directoryShell: {
      borderRadius: 16,
      backgroundColor: colors.background.card,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: "hidden",
      ...Theme.shadows.sm,
    },
    categoryBlock: {
      backgroundColor: colors.background.card,
    },
    categoryBlockBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.divider,
    },
    categoryHeader: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 10,
      gap: 10,
    },
    categoryIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryCopy: {
      flex: 1,
      minWidth: 0,
    },
    categoryTitle: {
      fontSize: 14,
      fontFamily: Fonts.bold,
      color: colors.text.primary,
    },
    categorySubtitle: {
      fontSize: 11,
      fontFamily: Fonts.regular,
      color: colors.text.secondary,
      marginTop: 1,
    },
    divider: {
      height: 1,
      backgroundColor: colors.divider,
      marginHorizontal: 14,
    },
    item: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      minHeight: 64,
      paddingVertical: 10,
      paddingHorizontal: 14,
    },
    itemPressed: {
      backgroundColor: colors.action.hover,
    },
    itemLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      flex: 1,
      minWidth: 0,
    },
    itemIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1,
      borderColor: isDark ? colors.action.selected : colors.border,
    },
    itemTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    itemText: {
      fontSize: 13,
      fontFamily: Fonts.bold,
      color: colors.text.primary,
    },
    itemDescription: {
      fontSize: 11,
      fontFamily: Fonts.regular,
      color: colors.text.secondary,
      marginTop: 2,
    },
    itemRight: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    badge: {
      minWidth: 24,
      paddingHorizontal: 6,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.status.error,
      justifyContent: "center",
      alignItems: "center",
    },
    badgeText: {
      fontSize: 10,
      fontFamily: Fonts.bold,
      color: colors.text.inverse,
    },
    emptyState: {
      minHeight: 156,
      alignItems: "center",
      justifyContent: "center",
      padding: 18,
    },
    emptyTitle: {
      fontSize: 14,
      fontFamily: Fonts.bold,
      color: colors.text.primary,
      marginTop: 10,
    },
    emptyText: {
      fontSize: 12,
      fontFamily: Fonts.regular,
      color: colors.text.secondary,
      marginTop: 3,
    },
  });
