export {
	CheckRoute,
	placeOrder,
	updateOrder,
	batchUpdate,
	editOrder,
	getOrderBasedOnDate,
	getActiveOrders,
	getActiveOrdersAdmin,
	getOrderDetails,
	updateOrderToDelivered,
	getOrdersBetweenDate,
	deleteImage,
	deleteOrder,
	getOrdersBasedOnUserId,
	getAllOrders,
} from "@src/api/order";
