import { StyleSheet } from 'react-native';
import type { AppTheme } from '@src/constants/Theme';
import { Fonts } from '@src/constants/Fonts';
import { HAIRLINE, RADIUS } from '@src/shared/ui/designLanguage';

export const createHomeRedesignStyles = (colors: AppTheme['colors'], isDark: boolean) =>
  StyleSheet.create({
    section: { gap: 14 },
    sectionHeader: { gap: 5, paddingHorizontal: 2 },
    sectionTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: -0.35,
    },
    sectionBody: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 21,
    },
    intro: {
      gap: 18,
      paddingTop: 14,
      paddingBottom: 4,
    },
    routeTag: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    routeDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.accent.amber,
    },
    routeTagText: {
      color: isDark ? colors.primary.light : colors.primary.dark,
      fontFamily: Fonts.bold,
      fontSize: 12,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    introTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.black,
      fontSize: 34,
      lineHeight: 39,
      letterSpacing: -0.8,
      maxWidth: 360,
    },
    introBody: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 16,
      lineHeight: 24,
      maxWidth: 360,
    },
    routeLine: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 58,
      borderTopWidth: HAIRLINE,
      borderBottomWidth: HAIRLINE,
      borderColor: colors.border,
    },
    routePlace: { flex: 1, gap: 2 },
    routePlaceRight: { alignItems: 'flex-end' },
    routeLabel: {
      color: colors.text.disabled,
      fontFamily: Fonts.medium,
      fontSize: 11,
    },
    routeCity: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 16,
    },
    routeModes: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      paddingHorizontal: 14,
    },
    routeModeRule: { width: 26, height: 1, backgroundColor: colors.border },
    indexList: {
      borderTopWidth: HAIRLINE,
      borderColor: colors.border,
    },
    indexRow: {
      minHeight: 78,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      borderBottomWidth: HAIRLINE,
      borderColor: colors.border,
      paddingVertical: 12,
      paddingHorizontal: 2,
    },
    indexRowPressed: { opacity: 0.68, transform: [{ scale: 0.99 }] },
    indexNumber: {
      width: 30,
      color: colors.text.disabled,
      fontFamily: Fonts.medium,
      fontSize: 12,
      fontVariant: ['tabular-nums'],
    },
    indexIcon: {
      width: 42,
      height: 42,
      borderRadius: RADIUS.control,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background.paper,
    },
    indexCopy: { flex: 1, minWidth: 0, gap: 3 },
    indexTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 16,
      lineHeight: 20,
    },
    indexSubtitle: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 20,
    },
    laneList: { gap: 10 },
    lane: {
      minHeight: 112,
      borderRadius: RADIUS.card,
      borderWidth: HAIRLINE,
      borderColor: colors.border,
      backgroundColor: colors.background.card,
      padding: 16,
      gap: 15,
    },
    lanePressed: { opacity: 0.72 },
    laneTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    laneMarker: {
      width: 42,
      height: 42,
      borderRadius: RADIUS.control,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background.paper,
    },
    laneCopy: { flex: 1, minWidth: 0, gap: 2 },
    laneTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 17,
    },
    laneMeta: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 20,
    },
    laneFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderTopWidth: HAIRLINE,
      borderColor: colors.border,
      paddingTop: 12,
    },
    laneTime: {
      color: isDark ? colors.primary.light : colors.primary.dark,
      fontFamily: Fonts.bold,
      fontSize: 14,
      fontVariant: ['tabular-nums'],
    },
    laneAction: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 14,
    },
    journeyList: { gap: 0 },
    journeyRow: { flexDirection: 'row', gap: 14, minHeight: 82 },
    journeyRail: { width: 26, alignItems: 'center' },
    journeyNode: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary.main,
    },
    journeyNodeText: {
      color: colors.text.inverse,
      fontFamily: Fonts.bold,
      fontSize: 11,
      fontVariant: ['tabular-nums'],
    },
    journeyRule: { flex: 1, width: 1, backgroundColor: colors.border },
    journeyCopy: { flex: 1, gap: 4, paddingBottom: 22 },
    journeyTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 15,
      lineHeight: 20,
    },
    journeyBody: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 20,
    },
    accountCard: {
      borderRadius: RADIUS.card,
      borderWidth: HAIRLINE,
      borderColor: colors.border,
      backgroundColor: colors.background.card,
      padding: 18,
      gap: 16,
    },
    accountTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 20,
      lineHeight: 26,
    },
    accountBody: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 21,
    },
    accountButton: {
      minHeight: 50,
      borderRadius: RADIUS.control,
      backgroundColor: isDark ? colors.primary.light : colors.primary.dark,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
      paddingHorizontal: 18,
    },
    accountButtonPressed: { opacity: 0.78, transform: [{ scale: 0.99 }] },
    accountButtonText: {
      color: colors.text.inverse,
      fontFamily: Fonts.bold,
      fontSize: 15,
    },
    serviceList: {
      borderTopWidth: HAIRLINE,
      borderColor: colors.border,
    },
    serviceRow: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderBottomWidth: HAIRLINE,
      borderColor: colors.border,
      paddingVertical: 10,
      paddingHorizontal: 2,
    },
    serviceIcon: {
      width: 36,
      height: 36,
      borderRadius: RADIUS.control,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background.card,
    },
    serviceCopy: { flex: 1, minWidth: 0, gap: 2 },
    serviceTitle: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 15,
      lineHeight: 20,
    },
    serviceBody: {
      color: colors.text.secondary,
      fontFamily: Fonts.regular,
      fontSize: 14,
      lineHeight: 20,
    },
    contactList: { gap: 10 },
    contactButton: {
      minHeight: 50,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: RADIUS.control,
      borderWidth: HAIRLINE,
      borderColor: colors.border,
      backgroundColor: colors.background.card,
      paddingHorizontal: 14,
    },
    contactCopy: { flex: 1, minWidth: 0, gap: 2 },
    contactName: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 15,
    },
    contactPhone: {
      color: isDark ? colors.primary.light : colors.primary.dark,
      fontFamily: Fonts.medium,
      fontSize: 14,
    },
    contactButtonPressed: { opacity: 0.68 },
    profileRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    profileChip: {
      minHeight: 38,
      justifyContent: 'center',
      borderRadius: RADIUS.control,
      borderWidth: HAIRLINE,
      borderColor: colors.border,
      backgroundColor: colors.background.card,
      paddingHorizontal: 12,
    },
    profileChipText: {
      color: colors.text.primary,
      fontFamily: Fonts.bold,
      fontSize: 13,
    },
  });
