import { StyleSheet } from 'react-native';

export const createStyles = (colors: any) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    sheet: {
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      maxHeight: '90%',
      backgroundColor: colors.background.card,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      padding: 16,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerLeft: {
      flex: 1,
    },
    title: {
      color: colors.text.primary,
      fontSize: 18,
      fontWeight: '800',
    },
    subtitle: {
      color: colors.text.secondary,
      fontSize: 14,
      marginTop: 2,
    },
    iconButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background.paper,
    },
    scrollContent: {
      padding: 16,
      gap: 12,
      paddingBottom: 24,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 4,
    },
    summaryBox: {
      borderRadius: 10,
      padding: 14,
      gap: 8,
      backgroundColor: colors.background.paper,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    summaryLabel: {
      fontSize: 13,
      color: colors.text.secondary,
    },
    summaryValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text.primary,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 4,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text.primary,
    },
    selectAllText: {
      color: colors.primary.main,
      fontSize: 13,
      fontWeight: '700',
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 24,
      gap: 8,
    },
    emptyText: {
      color: colors.text.disabled,
      fontSize: 14,
      fontWeight: '600',
    },
    goodsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background.paper,
    },
    goodsRowSelected: {
      backgroundColor: colors.primary.main + '08',
      borderColor: colors.primary.main + '40',
    },
    goodsText: {
      flex: 1,
    },
    goodsName: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text.primary,
    },
    goodsMeta: {
      fontSize: 12,
      color: colors.text.secondary,
      marginTop: 2,
    },
    input: {
      minHeight: 46,
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      color: colors.text.primary,
      borderColor: colors.border,
      backgroundColor: colors.background.default,
    },
    reasonInput: {
      minHeight: 60,
      paddingTop: 10,
      textAlignVertical: 'top',
    },
    preview: {
      color: colors.text.primary,
      fontSize: 14,
      fontWeight: '700',
    },
    validationBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 10,
      borderRadius: 8,
      backgroundColor: colors.status.error + '12',
    },
    validationText: {
      flex: 1,
      color: colors.status.error,
      fontSize: 13,
      fontWeight: '600',
    },
    readOnlyBox: {
      borderRadius: 10,
      padding: 14,
      gap: 8,
    },
    readOnlyTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    noteBox: {
      borderRadius: 8,
      padding: 10,
      backgroundColor: colors.background.paper,
      gap: 4,
      marginTop: 4,
    },
    noteLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.text.secondary,
      textTransform: 'uppercase',
    },
    noteText: {
      fontSize: 13,
      color: colors.text.primary,
      lineHeight: 18,
    },
    actions: {
      flexDirection: 'row',
      gap: 10,
      padding: 16,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    rejectButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.status.error + '12',
      borderWidth: 1,
      borderColor: colors.status.error + '30',
    },
    rejectText: {
      color: colors.status.error,
      fontSize: 14,
      fontWeight: '700',
    },
    approveButton: {
      flex: 1,
      minHeight: 48,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.status.success,
    },
    approveText: {
      color: colors.text.inverse,
      fontSize: 14,
      fontWeight: '800',
    },
    disabled: {
      opacity: 0.45,
    },
  });
