import { StyleSheet } from "react-native";

export const createStyles = (colors: any, isDark?: boolean) => StyleSheet.create({
  wrapper: {
    marginBottom: 12,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background.card,
    borderRadius: 16,
    padding: 14,
    shadowColor: colors.neutral[900],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
  },
  cardPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  blockedCard: {
    backgroundColor: colors.feedback.errorBg,
  },
  selectedCard: {
    borderWidth: 2,
    borderColor: colors.primary.main,
    backgroundColor: isDark ? `${colors.primary.main}20` : `${colors.primary.main}10`,
  },
  accentBorder: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.text.inverse,
  },
  info: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  name: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.text.primary,
    flex: 1,
    marginRight: 8,
  },
  blockedBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.feedback.errorBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 20,
    gap: 4,
  },
  blockedText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.status.error,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
    gap: 6,
  },
  phone: {
    fontSize: 13,
    color: colors.text.secondary,
    fontWeight: "500",
  },
  email: {
    fontSize: 12,
    color: colors.text.secondary,
    fontWeight: "400",
    flex: 1,
  },
  quickActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginRight: 6,
  },
  quickBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: colors.background.paper,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.neutral[200],
  },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  actionButton: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  blockButton: {
    backgroundColor: colors.feedback.errorBg,
  },
  unblockButton: {
    backgroundColor: colors.feedback.successBg,
  },
  deleteButton: {
    backgroundColor: colors.feedback.errorBg,
  },
});
