import { StyleSheet } from "react-native";
import { Theme } from "@src/constants/Theme";

export const getStyles = (colors: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background.default,
  },
  scrollContent: {
    flexGrow: 1,
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 48,
    paddingBottom: 32,
  },
  iconWrapper: {
    marginBottom: 16,
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: colors.status.success + '15',
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: colors.text.primary,
    marginBottom: 24,
    textAlign: "center",
  },
  card: {
    width: "100%",
    backgroundColor: colors.background.card,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: colors.primary.main,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
  },
  label: {
    fontSize: 14,
    color: colors.text.secondary,
    fontWeight: "500",
  },
  value: {
    fontSize: 14,
    color: colors.text.primary,
    fontWeight: "600",
    flexShrink: 1,
    textAlign: "right",
    marginLeft: 12,
  },
  divider: {
    height: 1,
    backgroundColor: colors.neutral[100],
  },
  verificationCode: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.primary.main,
    letterSpacing: 1,
  },
  valueWithCopy: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  copyButton: {
    padding: 4,
    backgroundColor: colors.neutral[100],
    borderRadius: 6,
  },
  downloadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    backgroundColor: colors.primary.main + '10',
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: colors.primary.main,
  },
  downloadButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary.main,
  },
  generatingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    paddingVertical: 14,
    marginBottom: 12,
  },
  generatingText: {
    fontSize: 14,
    color: colors.text.disabled,
    fontStyle: "italic",
  },
  whatsappButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    backgroundColor: colors.status.success,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 12,
  },
  whatsappButtonText: {
    color: colors.text.inverse,
    fontSize: 16,
    fontWeight: "700",
  },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    backgroundColor: colors.background.card,
    borderRadius: 12,
    paddingVertical: 14,
    marginBottom: 12,
    borderWidth: 1.5,
    borderColor: colors.primary.main,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.primary.main,
  },
  backTextButton: {
    paddingVertical: 12,
  },
  backTextButtonText: {
    fontSize: 15,
    color: colors.text.secondary,
    fontWeight: "500",
  },
  disabled: {
    opacity: 0.6,
  },
});
