import { StyleSheet } from 'react-native';
import { Fonts } from '@src/constants/Fonts';

export const createStyles = (colors: any, isDark?: boolean) =>
  StyleSheet.create({
    container: {
      margin: 12,
      padding: 16,
      borderRadius: 16,
      backgroundColor: colors.background.card,
      elevation: 2,
      shadowColor: colors.neutral[900],
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    },
    topRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 16,
    },
    clientSection: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    avatar: {
      width: 50,
      height: 50,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    avatarText: {
      fontSize: 18,
      fontWeight: '700',
      fontFamily: Fonts.bold,
    },
    clientInfo: {
      flex: 1,
    },
    clientName: {
      fontSize: 17,
      fontWeight: '600',
      color: colors.text.primary,
      fontFamily: Fonts.semiBold,
      marginBottom: 2,
    },
    codeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    orderCode: {
      fontSize: 13,
      color: colors.text.secondary,
      fontFamily: Fonts.medium,
      letterSpacing: 0.3,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 16,
      gap: 4,
    },
    statusText: {
      fontSize: 11,
      fontWeight: '600',
      fontFamily: Fonts.semiBold,
    },
    middleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 14,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    shippingBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      gap: 5,
    },
    shippingText: {
      fontSize: 12,
      fontWeight: '600',
      fontFamily: Fonts.semiBold,
    },
    priceContainer: {
      alignItems: 'flex-end',
    },
    priceLabel: {
      fontSize: 11,
      color: colors.text.secondary,
      fontFamily: Fonts.medium,
      marginBottom: 2,
    },
    priceValue: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text.primary,
      fontFamily: Fonts.bold,
    },
    unitPriceText: {
      fontSize: 12,
      color: colors.text.secondary,
      fontFamily: Fonts.medium,
      marginTop: 2,
    },
    paymentRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    paymentLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    paymentStatusText: {
      fontSize: 13,
      fontWeight: '600',
      fontFamily: Fonts.semiBold,
    },
    linkedBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primary.main,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      gap: 3,
    },
    linkedText: {
      fontSize: 10,
      color: colors.text.inverse,
      fontWeight: '600',
      fontFamily: Fonts.semiBold,
    },
    containerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 14,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.background.paper,
    },
    containerChipText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: colors.text.primary,
      fontFamily: Fonts.semiBold,
      letterSpacing: 0.2,
    },
    quickActions: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 14,
      paddingTop: 14,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    quickAction: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingVertical: 10,
      borderRadius: 12,
      backgroundColor: colors.background.paper,
    },
    quickActionLabel: {
      fontSize: 11,
      fontWeight: '600',
      fontFamily: Fonts.semiBold,
    },
  });

export default createStyles;
